services:
  todo-list:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_NAME=todo-list
      - DB_USER=postgres
      - DB_PASSWORD=todo-list
      - DB_HOST=todo-list-db
      - DB_PORT=5432
    restart: on-failure

  todo-list-db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=todo-list
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=todo-list
    ports:
      - "5432:5432"
    restart: on-failure

