services:
  todo-list:
    build: .
    command: python todo_list/manage.py run -h 0.0.0.0 -p 8080
    ports:
      - 8080:8080
    environment:
      - DB_NAME=todo-list
      - DB_USER=todo-list
      - DB_PASSWORD=todo-list
      - DB_HOST=todo-list-db
      - DB_PORT=5432
    env_file:
      - ./.env
    depends_on:
      - todo-list-db
    restart: on-failure

  todo-list-db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=todo-list
      - POSTGRES_USER=todo-list
      - POSTGRES_PASSWORD=todo-list
    ports:
      - "5433:5432"
    restart: on-failure

