services:
  todo-list:
    build: .
    command: python todo_list/manage.py run -h 0.0.0.0 -p 8080
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - todo-list-db
    networks:
      - custom
    restart: on-failure

  todo-list-db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=todo-list
      - POSTGRES_USER=todo-list
      - POSTGRES_PASSWORD=todo-list
    ports:
      - "5432:5432"
    volumes:
      - todolist-db-data:/var/lib/postgresql/data
    networks:
      - custom
    restart: on-failure

networks:
  custom:
    driver: bridge

volumes:
  todolist-db-data:


